############################################################
@local = https://localhost:7000
@deploy = https://abi-cache.extensivlyon.coffee

############################################################
### local test requests
POST {{local}}/getABI
content-type: application/json

{
    "authCode": "deadbeef",
    "address": "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c"
}


### local test requests
POST {{local}}/getABI
content-type: application/json

{
    "authCode": "deadbeef",
    "address": "0x5c872500c00565505f3624ab435c222e558e9ff8"
}


############################################################
### deploy test request
POST {{deploy}}/getABI
content-type: application/json

{
    "authCode": "deadbeef",
    "address": "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c"
}
